version: "3.3"
services:
  fastapi:
    build:
      context: ./server
    container_name: kdo-api
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./kdoapp/public/kdos:/shared/kdos
    env_file:
      - .env

  nextjs:
    build:
      context: ./kdoapp
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_THEME: ${NEXT_PUBLIC_THEME}
    depends_on:
      - fastapi
    container_name: kdo-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./kdoapp/public/kdos:/app/public/kdos
    env_file:
      - .env
