version: "3.3"
services:
  fastapi:
    build:
      context: ./server
    container_name: kdo-api
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./kdoapp/public/kdos:/shared/kdos
    env_file:
      - .env

  nextjs:
    build:
      context: . # on envoie toute la racine
      dockerfile: kdoapp/Dockerfile # le Dockerfile n’a pas bougé
    env_file: # tu gardes ça pour le runtime
      - .env
    container_name: kdo-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./kdoapp/public/kdos:/app/public/kdos
