import type { Metadata } from 'next';
import { Nav } from '@/components/Nav';
import { Footer } from '@/components/Footer';
import Snowflakes from '@/components/Snowflakes';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import { THEMES } from '@/lib/theme';
import { getTheme } from '@/lib/theme.server';
import './globals.css';

// Le thème est lu en base à chaque requête : aucune page ne doit être figée au build.
export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export async function generateMetadata(): Promise<Metadata> {
  const theme = await getTheme();
  return {
    title: THEMES[theme].appTitle,
    description: 'Generated by create next app',
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getTheme();
  const themeConfig = THEMES[theme];

  return (
    <html lang="fr-FR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${themeConfig.bodyClass} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider theme={theme}>
          <Nav />
          <div className="page-gradient flex-1 flex flex-col relative overflow-hidden animate-gradient">
            {themeConfig.showSnowflakes && <Snowflakes />}
            <main className="flex-1">{children}</main>
            {themeConfig.showSnowflakes && <div className="h-28" />}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
