import type { Metadata } from 'next';
import { Nav } from '@/components/Nav';
import { Footer } from '@/components/Footer';
import Snowflakes from '@/components/Snowflakes';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const theme = process.env.NEXT_PUBLIC_THEME || 'default';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: theme === 'christmas' ? 'Liste de Noël !' : "Liste d'anniversaire",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr-FR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Nav />
        <div
          className={`
            flex-1
            flex
            flex-col
            relative
            overflow-hidden
            ${
              theme === 'christmas'
                ? 'bg-gradient-to-br from-red-700 via-green-800 to-red-900'
                : 'bg-gradient-to-br from-sky-400 via-indigo-500 to-violet-600'
            }
            animate-gradient
          `}
        >
          {theme === 'christmas' && <Snowflakes />}
          <main className="flex-1">{children}</main>
          {theme === 'christmas' && <div className="h-28" />}
        </div>
        <Footer />
      </body>
    </html>
  );
}
