import type { Metadata } from 'next';
import { Nav } from '@/components/Nav';
import { Footer } from '@/components/Footer';
import Snowflakes from '@/components/Snowflakes';
import { Geist, Geist_Mono } from 'next/font/google';
import { themeConfig } from '@/lib/theme';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: themeConfig.appTitle,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr-FR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${themeConfig.bodyClass} antialiased min-h-screen flex flex-col`}
      >
        <Nav />
        <div className="page-gradient flex-1 flex flex-col relative overflow-hidden animate-gradient">
          {themeConfig.showSnowflakes && <Snowflakes />}
          <main className="flex-1">{children}</main>
          {themeConfig.showSnowflakes && <div className="h-28" />}
        </div>
        <Footer />
      </body>
    </html>
  );
}
